### PR TITLE
Use vallidations/validators as computed property

### PR DESCRIPTION
**Pull request by vvscode**
Motivation: allow to use ```validations``` as computed property

### CODE REVIEW

**Comment by bcardarella** [comment]
I'm not sure what the goal here is, there is no test that demonstrates the desired behavior

**Comment by vvscode** [comment]
@bcardarelia -- are they really need? All current tests works fine -- that's mean that all ok. But it 'validations' will be declared as ```computed``` - it will do it by standart ember mechanism. If, you suppose, that it costs to add tests, I'll do it

**Comment by bcardarella** [comment]
@vvscode if your intent is to add a new expected behavior then yes it is necessary

**Comment by vvscode** [comment]
@bcardarella  Ok, I see. Sorry -- for me it looks like small refactoring which checked by existing tests. Add case for computed ```validations```

**Comment by bcardarella** [comment]
@vvscode thank you. So now that I'm seeing the test I can see where you're going with this. I agree that fetching validations by CP is better. I'm curious if this is a complete feature though. If the validations are being retrieved via CP that implies the rules can be recomputed at any time. I suspect that the current implementation would not support this and could lead to confusion with people who are expecting to get that behavior. Thoughts?

**Comment by vvscode** [comment]
@bcardarella  for some of our validations we need pass container into  -- so, currently we can create module-variable to save there container and later use it, but it's ugly

**Comment by vvscode** [comment]
@bcardarella  I didn't know what behavior can be expected for recalculation this property, my main goal -- allow passing data / generating rules once per instance

**Comment by vihryn** [comment]
@bcardarella It will be useful when validations will depend of other properties. For example, messages changes.

**Comment by bcardarella** [comment]
@vihryn right, this is a scenario that is not being covered by this PR. If the CP depends on another property then the validations will recompute and potentially break

**Comment by vvscode** [comment]
@bcardarella  @vihryn  mean that it's depends on initial values ( yep, this PR  not covered changing validations on the fly )

**Comment by ebaranov** [comment]
Ohh gosh, is here! Thanks @vvscode for such improvement. 
It's really fine if we'll have opportunities to use computable properties in validations.

**Comment by bcardarella** [comment]
@ebaranov I suspect this does not cover what you think it might. This PR does not change out the observers over to CPs. It simply changes the retrieval.

**Comment by vvscode** [comment]
@bcardarella  about recalculations -- will be ok, if I'll recreate ( removeObservers/addObservers ) on property change?

**Comment by bcardarella** [comment]
@vvscode I'm not following, can you give me more detail?

**Comment by vvscode** [comment]
@bcardarella  if CP```validatons`` changed -- remove all observers ( created by ember-validation ) and re-create them again based on new ```validations```?

**Comment by bcardarella** [comment]
I don't believe that is the correct direction. I think that the CP effort has to be wholesale, and not attempt to rewrite things on the fly. The entire library has to be rewritten to take CPs into account over its current observer-style

**Comment by martndemus** [comment]
I am going to close this PR for now, feel free to reopen this PR if you feel like it's still relevant and we should take a look at it. If you do, please make sure the code is rebased against master.

**Pull request closed without merging**
