### PR TITLE
Adding support for overriding default messages

### PR DESCRIPTION
**Pull request by Hanastaroth**
As I am using [FormatJS - Ember Intl](http://formatjs.io/ember/) , I needed a way to override default message without using ember-i18n. 
This is the way I came up with. 

This may also be a workaround for the issue #224 

Let me know if you see any better way to do it.

### CODE REVIEW

**Comment by Hanastaroth** [comment]
Build failed, looks like an error appear while doing some cleanup before pushing...

**Comment by RuslanZavacky** [comment]
@Hanastaroth any progress on this?

**Comment by Hanastaroth** [comment]
Since I reopened the pull request ? No. 
But as there are conflicts, I will do some merging on my fork to update this pull request.

**Comment by Hanastaroth** [comment]
Merge done and conflicts resolved :)

**Comment by bcardarella** [comment]
I like the direction but I'd want to make some change:

1. I think instead of `validation:messages` the messages should be stored in a regular service object. For example `app/services/validations` then there should be a `messages` object on that service object. This allows for a cleaner directory structure by not introducing a new `validations` directory in addition to the already expected `validators` directory. This also allows the service object to be repurposed for other things.
2. The default service object should be stored in `addon/services/validations`. Then `app/services/validations` should `import` and `export` the object. This will allow others to provide their own default overrides cleanly.
3. The default service object should include the default messages included with this library. This will allow your `getMessage` function to cleanly just pull off of `services:validations` instead of the conditional delegation to `Messages` if there is a container lookup miss.

**Comment by Hanastaroth** [comment]
I've proposed a fast way to work with my needs, but it's clearly not as clean as what you have in mind. 

If you need any help to do this, feel free to ask. I can take some time on my working hours if necessary.

**Comment by bcardarella** [comment]
@Hanastaroth I'm not sure what you're saying... are you saying that I have to take the PR "as is" and you're not going to take my feedback into consideration?

**Comment by taras** [comment]
It seems that @bcardarella did a great job of outlying what changes need to be made for this PR to be mergeable. 

@Hanastaroth, you mentioned that you can take some time out of work day to hep. You could help by making the changes that @bcardarella suggested.

**Comment by bcardarella** [comment]
@Hanastaroth if we're both free at the same time I'm open to doing a Google Hangout with you to pair on making the necessary changes

**Comment by Hanastaroth** [comment]
@bcardarella  I think I didn't understand what you were saying, and I answer as if you were just going to take the idea and do the change directly without the PR. 

I am really thankful for your feedback as I'm just a beginner in ember. I'm going to start working on it tomorrow and I think a new version could be available on sunday.

**Comment by Hanastaroth** [comment]
I love the night when I can't sleep. 
@bcardarella here a new version, ready for any feedback on the modification I've done. 
I'll take them tomorrow

**Comment by Hanastaroth** [comment]
@bcardarella Hi, any news or new feedback on this ? :)

**Comment by Hanastaroth** [comment]
Closing PR as it's now quite old. A new one will be opened to start from a clean state.

**Pull request closed without merging**
