### PR TITLE
Add support for validations as computed property

### PR DESCRIPTION
**Pull request by fenichelar**
#289

### CODE REVIEW

**Comment by fenichelar** [comment]
I know this isn't an ideal way to handle this but adding 2 lines of code (arguably 1), makes computed validations not error. The validators won't update if the computed property does but at least you can calculate validations at run time. This is useful if you just need to format the validations for this addon or other simple cases where validations never change.

**Comment by fenichelar** [comment]
Thoughts?

**Comment by bcardarella** [comment]
I am going to be releasing 2.0.0 as-is and head in another direction with the library. There have been many use cases that have come about over the years and I'm convinced that the implementation of ember-validations cannot solve them. It requires a reboot. It should significantly simplify the library and make it more flexible. I hope to start work on it during Ember Conf.

**Comment by fenichelar** [comment]
I totally understand and support, but this change is so simple and fixes a big issue immediately. At least computed properties work. By no means the best way to do it but a very simple "hack" to make it work.

**Comment by bcardarella** [comment]
The change is more systemic than it might appear. I'd prefer not to bring this in and make this change for people last minute before release of software that has been in alpha/beta for nearly two years.

**Comment by martndemus** [comment]
I am going to close this PR for now, feel free to reopen this PR if you feel like it's still relevant and we should take a look at it. If you do, please make sure the code is rebased against master.

**Pull request closed without merging**
