### PR TITLE
Update Ember.keys to Object.keys

### PR DESCRIPTION
**Pull request by clairton**

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1:

**Comment by kmiyashiro** [comment]
:+1:

**Comment by jrjohnson** [comment]
Sorry to bump, but I'm not exaggerating when I say that this is the only thing holding our app back from going to 2.0 and we are going to have to use a fork temporarily so we can move forward and this looks like a straight forward one click merge.

**Comment by bcardarella** [comment]
All set! :)

**Comment by jrjohnson** [comment]
Thanks a lot!  That is a really big help.

**Comment by clairton** [comment]
Thanks so much!

**Pull request merged**
