### PR TITLE
Adding message service

### PR DESCRIPTION
**Pull request by Hanastaroth**
Hi, 

As the previous pull request was quite old, I decided to redo the work from a clean state. 
Here is a new pull request which will allow the use of a message service for validations label. 

See #257 for historic. 

Regards,

### CODE REVIEW

**Comment by dopudesign** [comment]
:+1:

**Comment by makepanic** [comment]
Do we really need a service for overwriting the default messages?
We could easily solve this issue by using the environment by reading a specific field, like `ENV['ember-validations']` that contains the messages. 
That's the same way [ember-simple-auth](https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/app/initializers/ember-simple-auth.js#L11) and [ember-cli-mirage](https://github.com/samselikoff/ember-cli-mirage/blob/master/app/initializers/ember-cli-mirage.js#L15) allow the user to change default configuration values.

For ember-validations it could look like this:

```
// ember-validations/app/initializers/ember-validations.js
import ENV from '../config/environment';
import messages from 'ember-validations/messages';
import Ember from 'ember';

const {extend} = Ember.$;

export function initialize(/* container, application */) {
  if (ENV.hasOwnProperty('ember-validations') && ENV['ember-validations'].hasOwnProperty('messages')) {
    messages.defaults = extend({}, messages.defaults, ENV['ember-validations'].messages);
  }
}

export default {
  name: 'ember-validations',
  initialize: initialize
};
```

And the addon user can define custom messages in his `config/environment.js` like this:

```
…
var ENV = {
  …
   'ember-validations': {
      messages: {
        inclusion: "n'est pas dans la liste",
        …
      }
  },
  …
};
…
```

I don't know if this will work for non ember-cli users though.

**Comment by Hanastaroth** [comment]
That could work. But what if you want your application to have multilingual support ?

**Comment by makepanic** [comment]
Yeah you're right.

I only followed "Adding support for overriding default messages" https://github.com/dockyard/ember-validations/pull/257 to this PR. 
The use-case I had in mind was to redefine the default messages once for a non-english app that has only one locale.
The disadvantage of using the initializer snippet above is that it won't be automatically be called in tests.

**Comment by martndemus** [comment]
I am going to close this PR for now, feel free to reopen this PR if you feel like it's still relevant and we should take a look at it. If you do, please make sure the code is rebased against master.

**Pull request closed without merging**
