### PR TITLE
Replaced bundeld Errors with DS.Errors

### PR DESCRIPTION
**Pull request by nobesnickr**
object to work with backend validation errors handled by Ember Data

### CODE REVIEW

**Comment by nobesnickr** [comment]
This PR is attempt to resolve https://github.com/dockyard/ember-validations/issues/363 . Will need to added backwards compatibility checks for and likely other repercussions of changing

**Comment by nobesnickr** [comment]
Can someone shed some light on Test 91? Confirmation Validator: message integration on model, prints message on Confirmation property

Not sure exactly where thats setup or what the expectation is. Should I change the test or is there some adjustments needed in code?

**Comment by sescobb27** [comment]
using `DS.Errors` as errors attribute fix all my issues with ember validations, thanks :)
```js
init: function () {
    this._super();
    this.errors = DS.Errors.create();
  },
```

**Comment by martndemus** [comment]
I am going to close this PR for now, feel free to reopen this PR if you feel like it's still relevant and we should take a look at it. If you do, please make sure the code is rebased against master.

**Pull request closed without merging**
